# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/demori/Downloads/CLion-2019.2.5/clion-2019.2.5/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/demori/Downloads/CLion-2019.2.5/clion-2019.2.5/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/demori/Documentos/Savime/Savime

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/demori/Documentos/Savime/Savime

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/demori/Downloads/CLion-2019.2.5/clion-2019.2.5/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/demori/Downloads/CLion-2019.2.5/clion-2019.2.5/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/demori/Downloads/CLion-2019.2.5/clion-2019.2.5/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/demori/Downloads/CLion-2019.2.5/clion-2019.2.5/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/demori/Downloads/CLion-2019.2.5/clion-2019.2.5/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/demori/Downloads/CLion-2019.2.5/clion-2019.2.5/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/demori/Downloads/CLion-2019.2.5/clion-2019.2.5/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/demori/Downloads/CLion-2019.2.5/clion-2019.2.5/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/demori/Documentos/Savime/Savime/CMakeFiles /home/demori/Documentos/Savime/Savime/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/demori/Documentos/Savime/Savime/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named savimec

# Build rule for target.
savimec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 savimec
.PHONY : savimec

# fast build rule for target.
savimec/fast:
	$(MAKE) -f CMakeFiles/savimec.dir/build.make CMakeFiles/savimec.dir/build
.PHONY : savimec/fast

#=============================================================================
# Target rules for targets named savime

# Build rule for target.
savime: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 savime
.PHONY : savime

# fast build rule for target.
savime/fast:
	$(MAKE) -f CMakeFiles/savime.dir/build.make CMakeFiles/savime.dir/build
.PHONY : savime/fast

#=============================================================================
# Target rules for targets named savime-bin

# Build rule for target.
savime-bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 savime-bin
.PHONY : savime-bin

# fast build rule for target.
savime-bin/fast:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/build
.PHONY : savime-bin/fast

#=============================================================================
# Target rules for targets named savime-test

# Build rule for target.
savime-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 savime-test
.PHONY : savime-test

# fast build rule for target.
savime-test/fast:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/build
.PHONY : savime-test/fast

#=============================================================================
# Target rules for targets named savime-staging

# Build rule for target.
savime-staging: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 savime-staging
.PHONY : savime-staging

# fast build rule for target.
savime-staging/fast:
	$(MAKE) -f CMakeFiles/savime-staging.dir/build.make CMakeFiles/savime-staging.dir/build
.PHONY : savime-staging/fast

client/client.o: client/client.cpp.o

.PHONY : client/client.o

# target to build an object file
client/client.cpp.o:
	$(MAKE) -f CMakeFiles/savimec.dir/build.make CMakeFiles/savimec.dir/client/client.cpp.o
.PHONY : client/client.cpp.o

client/client.i: client/client.cpp.i

.PHONY : client/client.i

# target to preprocess a source file
client/client.cpp.i:
	$(MAKE) -f CMakeFiles/savimec.dir/build.make CMakeFiles/savimec.dir/client/client.cpp.i
.PHONY : client/client.cpp.i

client/client.s: client/client.cpp.s

.PHONY : client/client.s

# target to generate assembly for a file
client/client.cpp.s:
	$(MAKE) -f CMakeFiles/savimec.dir/build.make CMakeFiles/savimec.dir/client/client.cpp.s
.PHONY : client/client.cpp.s

configuration/default_config_manager.o: configuration/default_config_manager.cpp.o

.PHONY : configuration/default_config_manager.o

# target to build an object file
configuration/default_config_manager.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/configuration/default_config_manager.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/configuration/default_config_manager.cpp.o
.PHONY : configuration/default_config_manager.cpp.o

configuration/default_config_manager.i: configuration/default_config_manager.cpp.i

.PHONY : configuration/default_config_manager.i

# target to preprocess a source file
configuration/default_config_manager.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/configuration/default_config_manager.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/configuration/default_config_manager.cpp.i
.PHONY : configuration/default_config_manager.cpp.i

configuration/default_config_manager.s: configuration/default_config_manager.cpp.s

.PHONY : configuration/default_config_manager.s

# target to generate assembly for a file
configuration/default_config_manager.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/configuration/default_config_manager.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/configuration/default_config_manager.cpp.s
.PHONY : configuration/default_config_manager.cpp.s

configuration/model_configuration_manager.o: configuration/model_configuration_manager.cpp.o

.PHONY : configuration/model_configuration_manager.o

# target to build an object file
configuration/model_configuration_manager.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/configuration/model_configuration_manager.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/configuration/model_configuration_manager.cpp.o
.PHONY : configuration/model_configuration_manager.cpp.o

configuration/model_configuration_manager.i: configuration/model_configuration_manager.cpp.i

.PHONY : configuration/model_configuration_manager.i

# target to preprocess a source file
configuration/model_configuration_manager.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/configuration/model_configuration_manager.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/configuration/model_configuration_manager.cpp.i
.PHONY : configuration/model_configuration_manager.cpp.i

configuration/model_configuration_manager.s: configuration/model_configuration_manager.cpp.s

.PHONY : configuration/model_configuration_manager.s

# target to generate assembly for a file
configuration/model_configuration_manager.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/configuration/model_configuration_manager.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/configuration/model_configuration_manager.cpp.s
.PHONY : configuration/model_configuration_manager.cpp.s

connection/default_connection_manager.o: connection/default_connection_manager.cpp.o

.PHONY : connection/default_connection_manager.o

# target to build an object file
connection/default_connection_manager.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/connection/default_connection_manager.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/connection/default_connection_manager.cpp.o
.PHONY : connection/default_connection_manager.cpp.o

connection/default_connection_manager.i: connection/default_connection_manager.cpp.i

.PHONY : connection/default_connection_manager.i

# target to preprocess a source file
connection/default_connection_manager.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/connection/default_connection_manager.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/connection/default_connection_manager.cpp.i
.PHONY : connection/default_connection_manager.cpp.i

connection/default_connection_manager.s: connection/default_connection_manager.cpp.s

.PHONY : connection/default_connection_manager.s

# target to generate assembly for a file
connection/default_connection_manager.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/connection/default_connection_manager.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/connection/default_connection_manager.cpp.s
.PHONY : connection/default_connection_manager.cpp.s

core/builder.o: core/builder.cpp.o

.PHONY : core/builder.o

# target to build an object file
core/builder.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/core/builder.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/core/builder.cpp.o
.PHONY : core/builder.cpp.o

core/builder.i: core/builder.cpp.i

.PHONY : core/builder.i

# target to preprocess a source file
core/builder.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/core/builder.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/core/builder.cpp.i
.PHONY : core/builder.cpp.i

core/builder.s: core/builder.cpp.s

.PHONY : core/builder.s

# target to generate assembly for a file
core/builder.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/core/builder.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/core/builder.cpp.s
.PHONY : core/builder.cpp.s

core/main.o: core/main.cpp.o

.PHONY : core/main.o

# target to build an object file
core/main.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/core/main.cpp.o
.PHONY : core/main.cpp.o

core/main.i: core/main.cpp.i

.PHONY : core/main.i

# target to preprocess a source file
core/main.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/core/main.cpp.i
.PHONY : core/main.cpp.i

core/main.s: core/main.cpp.s

.PHONY : core/main.s

# target to generate assembly for a file
core/main.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/core/main.cpp.s
.PHONY : core/main.cpp.s

core/metadata.o: core/metadata.cpp.o

.PHONY : core/metadata.o

# target to build an object file
core/metadata.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/core/metadata.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/core/metadata.cpp.o
.PHONY : core/metadata.cpp.o

core/metadata.i: core/metadata.cpp.i

.PHONY : core/metadata.i

# target to preprocess a source file
core/metadata.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/core/metadata.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/core/metadata.cpp.i
.PHONY : core/metadata.cpp.i

core/metadata.s: core/metadata.cpp.s

.PHONY : core/metadata.s

# target to generate assembly for a file
core/metadata.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/core/metadata.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/core/metadata.cpp.s
.PHONY : core/metadata.cpp.s

core/query_data_manager.o: core/query_data_manager.cpp.o

.PHONY : core/query_data_manager.o

# target to build an object file
core/query_data_manager.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/core/query_data_manager.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/core/query_data_manager.cpp.o
.PHONY : core/query_data_manager.cpp.o

core/query_data_manager.i: core/query_data_manager.cpp.i

.PHONY : core/query_data_manager.i

# target to preprocess a source file
core/query_data_manager.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/core/query_data_manager.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/core/query_data_manager.cpp.i
.PHONY : core/query_data_manager.cpp.i

core/query_data_manager.s: core/query_data_manager.cpp.s

.PHONY : core/query_data_manager.s

# target to generate assembly for a file
core/query_data_manager.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/core/query_data_manager.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/core/query_data_manager.cpp.s
.PHONY : core/query_data_manager.cpp.s

core/system_logger.o: core/system_logger.cpp.o

.PHONY : core/system_logger.o

# target to build an object file
core/system_logger.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/core/system_logger.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/core/system_logger.cpp.o
.PHONY : core/system_logger.cpp.o

core/system_logger.i: core/system_logger.cpp.i

.PHONY : core/system_logger.i

# target to preprocess a source file
core/system_logger.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/core/system_logger.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/core/system_logger.cpp.i
.PHONY : core/system_logger.cpp.i

core/system_logger.s: core/system_logger.cpp.s

.PHONY : core/system_logger.s

# target to generate assembly for a file
core/system_logger.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/core/system_logger.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/core/system_logger.cpp.s
.PHONY : core/system_logger.cpp.s

engine/aggregate.o: engine/aggregate.cpp.o

.PHONY : engine/aggregate.o

# target to build an object file
engine/aggregate.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/aggregate.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/aggregate.cpp.o
.PHONY : engine/aggregate.cpp.o

engine/aggregate.i: engine/aggregate.cpp.i

.PHONY : engine/aggregate.i

# target to preprocess a source file
engine/aggregate.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/aggregate.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/aggregate.cpp.i
.PHONY : engine/aggregate.cpp.i

engine/aggregate.s: engine/aggregate.cpp.s

.PHONY : engine/aggregate.s

# target to generate assembly for a file
engine/aggregate.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/aggregate.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/aggregate.cpp.s
.PHONY : engine/aggregate.cpp.s

engine/arithmetic.o: engine/arithmetic.cpp.o

.PHONY : engine/arithmetic.o

# target to build an object file
engine/arithmetic.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/arithmetic.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/arithmetic.cpp.o
.PHONY : engine/arithmetic.cpp.o

engine/arithmetic.i: engine/arithmetic.cpp.i

.PHONY : engine/arithmetic.i

# target to preprocess a source file
engine/arithmetic.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/arithmetic.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/arithmetic.cpp.i
.PHONY : engine/arithmetic.cpp.i

engine/arithmetic.s: engine/arithmetic.cpp.s

.PHONY : engine/arithmetic.s

# target to generate assembly for a file
engine/arithmetic.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/arithmetic.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/arithmetic.cpp.s
.PHONY : engine/arithmetic.cpp.s

engine/comparison.o: engine/comparison.cpp.o

.PHONY : engine/comparison.o

# target to build an object file
engine/comparison.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/comparison.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/comparison.cpp.o
.PHONY : engine/comparison.cpp.o

engine/comparison.i: engine/comparison.cpp.i

.PHONY : engine/comparison.i

# target to preprocess a source file
engine/comparison.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/comparison.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/comparison.cpp.i
.PHONY : engine/comparison.cpp.i

engine/comparison.s: engine/comparison.cpp.s

.PHONY : engine/comparison.s

# target to generate assembly for a file
engine/comparison.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/comparison.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/comparison.cpp.s
.PHONY : engine/comparison.cpp.s

engine/create_dataset.o: engine/create_dataset.cpp.o

.PHONY : engine/create_dataset.o

# target to build an object file
engine/create_dataset.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/create_dataset.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/create_dataset.cpp.o
.PHONY : engine/create_dataset.cpp.o

engine/create_dataset.i: engine/create_dataset.cpp.i

.PHONY : engine/create_dataset.i

# target to preprocess a source file
engine/create_dataset.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/create_dataset.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/create_dataset.cpp.i
.PHONY : engine/create_dataset.cpp.i

engine/create_dataset.s: engine/create_dataset.cpp.s

.PHONY : engine/create_dataset.s

# target to generate assembly for a file
engine/create_dataset.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/create_dataset.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/create_dataset.cpp.s
.PHONY : engine/create_dataset.cpp.s

engine/create_tar.o: engine/create_tar.cpp.o

.PHONY : engine/create_tar.o

# target to build an object file
engine/create_tar.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/create_tar.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/create_tar.cpp.o
.PHONY : engine/create_tar.cpp.o

engine/create_tar.i: engine/create_tar.cpp.i

.PHONY : engine/create_tar.i

# target to preprocess a source file
engine/create_tar.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/create_tar.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/create_tar.cpp.i
.PHONY : engine/create_tar.cpp.i

engine/create_tar.s: engine/create_tar.cpp.s

.PHONY : engine/create_tar.s

# target to generate assembly for a file
engine/create_tar.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/create_tar.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/create_tar.cpp.s
.PHONY : engine/create_tar.cpp.s

engine/create_tars.o: engine/create_tars.cpp.o

.PHONY : engine/create_tars.o

# target to build an object file
engine/create_tars.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/create_tars.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/create_tars.cpp.o
.PHONY : engine/create_tars.cpp.o

engine/create_tars.i: engine/create_tars.cpp.i

.PHONY : engine/create_tars.i

# target to preprocess a source file
engine/create_tars.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/create_tars.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/create_tars.cpp.i
.PHONY : engine/create_tars.cpp.i

engine/create_tars.s: engine/create_tars.cpp.s

.PHONY : engine/create_tars.s

# target to generate assembly for a file
engine/create_tars.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/create_tars.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/create_tars.cpp.s
.PHONY : engine/create_tars.cpp.s

engine/create_type.o: engine/create_type.cpp.o

.PHONY : engine/create_type.o

# target to build an object file
engine/create_type.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/create_type.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/create_type.cpp.o
.PHONY : engine/create_type.cpp.o

engine/create_type.i: engine/create_type.cpp.i

.PHONY : engine/create_type.i

# target to preprocess a source file
engine/create_type.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/create_type.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/create_type.cpp.i
.PHONY : engine/create_type.cpp.i

engine/create_type.s: engine/create_type.cpp.s

.PHONY : engine/create_type.s

# target to generate assembly for a file
engine/create_type.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/create_type.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/create_type.cpp.s
.PHONY : engine/create_type.cpp.s

engine/cross_join.o: engine/cross_join.cpp.o

.PHONY : engine/cross_join.o

# target to build an object file
engine/cross_join.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/cross_join.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/cross_join.cpp.o
.PHONY : engine/cross_join.cpp.o

engine/cross_join.i: engine/cross_join.cpp.i

.PHONY : engine/cross_join.i

# target to preprocess a source file
engine/cross_join.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/cross_join.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/cross_join.cpp.i
.PHONY : engine/cross_join.cpp.i

engine/cross_join.s: engine/cross_join.cpp.s

.PHONY : engine/cross_join.s

# target to generate assembly for a file
engine/cross_join.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/cross_join.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/cross_join.cpp.s
.PHONY : engine/cross_join.cpp.s

engine/default_engine.o: engine/default_engine.cpp.o

.PHONY : engine/default_engine.o

# target to build an object file
engine/default_engine.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/default_engine.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/default_engine.cpp.o
.PHONY : engine/default_engine.cpp.o

engine/default_engine.i: engine/default_engine.cpp.i

.PHONY : engine/default_engine.i

# target to preprocess a source file
engine/default_engine.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/default_engine.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/default_engine.cpp.i
.PHONY : engine/default_engine.cpp.i

engine/default_engine.s: engine/default_engine.cpp.s

.PHONY : engine/default_engine.s

# target to generate assembly for a file
engine/default_engine.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/default_engine.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/default_engine.cpp.s
.PHONY : engine/default_engine.cpp.s

engine/dimjoin.o: engine/dimjoin.cpp.o

.PHONY : engine/dimjoin.o

# target to build an object file
engine/dimjoin.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/dimjoin.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/dimjoin.cpp.o
.PHONY : engine/dimjoin.cpp.o

engine/dimjoin.i: engine/dimjoin.cpp.i

.PHONY : engine/dimjoin.i

# target to preprocess a source file
engine/dimjoin.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/dimjoin.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/dimjoin.cpp.i
.PHONY : engine/dimjoin.cpp.i

engine/dimjoin.s: engine/dimjoin.cpp.s

.PHONY : engine/dimjoin.s

# target to generate assembly for a file
engine/dimjoin.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/dimjoin.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/dimjoin.cpp.s
.PHONY : engine/dimjoin.cpp.s

engine/drop_dataset.o: engine/drop_dataset.cpp.o

.PHONY : engine/drop_dataset.o

# target to build an object file
engine/drop_dataset.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/drop_dataset.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/drop_dataset.cpp.o
.PHONY : engine/drop_dataset.cpp.o

engine/drop_dataset.i: engine/drop_dataset.cpp.i

.PHONY : engine/drop_dataset.i

# target to preprocess a source file
engine/drop_dataset.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/drop_dataset.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/drop_dataset.cpp.i
.PHONY : engine/drop_dataset.cpp.i

engine/drop_dataset.s: engine/drop_dataset.cpp.s

.PHONY : engine/drop_dataset.s

# target to generate assembly for a file
engine/drop_dataset.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/drop_dataset.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/drop_dataset.cpp.s
.PHONY : engine/drop_dataset.cpp.s

engine/drop_tar.o: engine/drop_tar.cpp.o

.PHONY : engine/drop_tar.o

# target to build an object file
engine/drop_tar.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/drop_tar.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/drop_tar.cpp.o
.PHONY : engine/drop_tar.cpp.o

engine/drop_tar.i: engine/drop_tar.cpp.i

.PHONY : engine/drop_tar.i

# target to preprocess a source file
engine/drop_tar.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/drop_tar.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/drop_tar.cpp.i
.PHONY : engine/drop_tar.cpp.i

engine/drop_tar.s: engine/drop_tar.cpp.s

.PHONY : engine/drop_tar.s

# target to generate assembly for a file
engine/drop_tar.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/drop_tar.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/drop_tar.cpp.s
.PHONY : engine/drop_tar.cpp.s

engine/drop_tars.o: engine/drop_tars.cpp.o

.PHONY : engine/drop_tars.o

# target to build an object file
engine/drop_tars.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/drop_tars.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/drop_tars.cpp.o
.PHONY : engine/drop_tars.cpp.o

engine/drop_tars.i: engine/drop_tars.cpp.i

.PHONY : engine/drop_tars.i

# target to preprocess a source file
engine/drop_tars.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/drop_tars.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/drop_tars.cpp.i
.PHONY : engine/drop_tars.cpp.i

engine/drop_tars.s: engine/drop_tars.cpp.s

.PHONY : engine/drop_tars.s

# target to generate assembly for a file
engine/drop_tars.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/drop_tars.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/drop_tars.cpp.s
.PHONY : engine/drop_tars.cpp.s

engine/drop_type.o: engine/drop_type.cpp.o

.PHONY : engine/drop_type.o

# target to build an object file
engine/drop_type.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/drop_type.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/drop_type.cpp.o
.PHONY : engine/drop_type.cpp.o

engine/drop_type.i: engine/drop_type.cpp.i

.PHONY : engine/drop_type.i

# target to preprocess a source file
engine/drop_type.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/drop_type.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/drop_type.cpp.i
.PHONY : engine/drop_type.cpp.i

engine/drop_type.s: engine/drop_type.cpp.s

.PHONY : engine/drop_type.s

# target to generate assembly for a file
engine/drop_type.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/drop_type.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/drop_type.cpp.s
.PHONY : engine/drop_type.cpp.s

engine/equijoin.o: engine/equijoin.cpp.o

.PHONY : engine/equijoin.o

# target to build an object file
engine/equijoin.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/equijoin.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/equijoin.cpp.o
.PHONY : engine/equijoin.cpp.o

engine/equijoin.i: engine/equijoin.cpp.i

.PHONY : engine/equijoin.i

# target to preprocess a source file
engine/equijoin.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/equijoin.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/equijoin.cpp.i
.PHONY : engine/equijoin.cpp.i

engine/equijoin.s: engine/equijoin.cpp.s

.PHONY : engine/equijoin.s

# target to generate assembly for a file
engine/equijoin.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/equijoin.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/equijoin.cpp.s
.PHONY : engine/equijoin.cpp.s

engine/filter.o: engine/filter.cpp.o

.PHONY : engine/filter.o

# target to build an object file
engine/filter.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/filter.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/filter.cpp.o
.PHONY : engine/filter.cpp.o

engine/filter.i: engine/filter.cpp.i

.PHONY : engine/filter.i

# target to preprocess a source file
engine/filter.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/filter.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/filter.cpp.i
.PHONY : engine/filter.cpp.i

engine/filter.s: engine/filter.cpp.s

.PHONY : engine/filter.s

# target to generate assembly for a file
engine/filter.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/filter.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/filter.cpp.s
.PHONY : engine/filter.cpp.s

engine/load_subtar.o: engine/load_subtar.cpp.o

.PHONY : engine/load_subtar.o

# target to build an object file
engine/load_subtar.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/load_subtar.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/load_subtar.cpp.o
.PHONY : engine/load_subtar.cpp.o

engine/load_subtar.i: engine/load_subtar.cpp.i

.PHONY : engine/load_subtar.i

# target to preprocess a source file
engine/load_subtar.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/load_subtar.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/load_subtar.cpp.i
.PHONY : engine/load_subtar.cpp.i

engine/load_subtar.s: engine/load_subtar.cpp.s

.PHONY : engine/load_subtar.s

# target to generate assembly for a file
engine/load_subtar.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/load_subtar.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/load_subtar.cpp.s
.PHONY : engine/load_subtar.cpp.s

engine/logical.o: engine/logical.cpp.o

.PHONY : engine/logical.o

# target to build an object file
engine/logical.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/logical.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/logical.cpp.o
.PHONY : engine/logical.cpp.o

engine/logical.i: engine/logical.cpp.i

.PHONY : engine/logical.i

# target to preprocess a source file
engine/logical.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/logical.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/logical.cpp.i
.PHONY : engine/logical.cpp.i

engine/logical.s: engine/logical.cpp.s

.PHONY : engine/logical.s

# target to generate assembly for a file
engine/logical.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/logical.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/logical.cpp.s
.PHONY : engine/logical.cpp.s

engine/misc/curl.o: engine/misc/curl.cpp.o

.PHONY : engine/misc/curl.o

# target to build an object file
engine/misc/curl.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/misc/curl.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/misc/curl.cpp.o
.PHONY : engine/misc/curl.cpp.o

engine/misc/curl.i: engine/misc/curl.cpp.i

.PHONY : engine/misc/curl.i

# target to preprocess a source file
engine/misc/curl.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/misc/curl.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/misc/curl.cpp.i
.PHONY : engine/misc/curl.cpp.i

engine/misc/curl.s: engine/misc/curl.cpp.s

.PHONY : engine/misc/curl.s

# target to generate assembly for a file
engine/misc/curl.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/misc/curl.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/misc/curl.cpp.s
.PHONY : engine/misc/curl.cpp.s

engine/misc/json.o: engine/misc/json.cpp.o

.PHONY : engine/misc/json.o

# target to build an object file
engine/misc/json.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/misc/json.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/misc/json.cpp.o
.PHONY : engine/misc/json.cpp.o

engine/misc/json.i: engine/misc/json.cpp.i

.PHONY : engine/misc/json.i

# target to preprocess a source file
engine/misc/json.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/misc/json.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/misc/json.cpp.i
.PHONY : engine/misc/json.cpp.i

engine/misc/json.s: engine/misc/json.cpp.s

.PHONY : engine/misc/json.s

# target to generate assembly for a file
engine/misc/json.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/misc/json.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/misc/json.cpp.s
.PHONY : engine/misc/json.cpp.s

engine/misc/prediction_model.o: engine/misc/prediction_model.cpp.o

.PHONY : engine/misc/prediction_model.o

# target to build an object file
engine/misc/prediction_model.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/misc/prediction_model.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/misc/prediction_model.cpp.o
.PHONY : engine/misc/prediction_model.cpp.o

engine/misc/prediction_model.i: engine/misc/prediction_model.cpp.i

.PHONY : engine/misc/prediction_model.i

# target to preprocess a source file
engine/misc/prediction_model.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/misc/prediction_model.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/misc/prediction_model.cpp.i
.PHONY : engine/misc/prediction_model.cpp.i

engine/misc/prediction_model.s: engine/misc/prediction_model.cpp.s

.PHONY : engine/misc/prediction_model.s

# target to generate assembly for a file
engine/misc/prediction_model.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/misc/prediction_model.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/misc/prediction_model.cpp.s
.PHONY : engine/misc/prediction_model.cpp.s

engine/predict.o: engine/predict.cpp.o

.PHONY : engine/predict.o

# target to build an object file
engine/predict.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/predict.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/predict.cpp.o
.PHONY : engine/predict.cpp.o

engine/predict.i: engine/predict.cpp.i

.PHONY : engine/predict.i

# target to preprocess a source file
engine/predict.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/predict.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/predict.cpp.i
.PHONY : engine/predict.cpp.i

engine/predict.s: engine/predict.cpp.s

.PHONY : engine/predict.s

# target to generate assembly for a file
engine/predict.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/predict.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/predict.cpp.s
.PHONY : engine/predict.cpp.s

engine/predictor.o: engine/predictor.cpp.o

.PHONY : engine/predictor.o

# target to build an object file
engine/predictor.cpp.o:
	$(MAKE) -f CMakeFiles/savime.dir/build.make CMakeFiles/savime.dir/engine/predictor.cpp.o
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/predictor.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/predictor.cpp.o
.PHONY : engine/predictor.cpp.o

engine/predictor.i: engine/predictor.cpp.i

.PHONY : engine/predictor.i

# target to preprocess a source file
engine/predictor.cpp.i:
	$(MAKE) -f CMakeFiles/savime.dir/build.make CMakeFiles/savime.dir/engine/predictor.cpp.i
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/predictor.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/predictor.cpp.i
.PHONY : engine/predictor.cpp.i

engine/predictor.s: engine/predictor.cpp.s

.PHONY : engine/predictor.s

# target to generate assembly for a file
engine/predictor.cpp.s:
	$(MAKE) -f CMakeFiles/savime.dir/build.make CMakeFiles/savime.dir/engine/predictor.cpp.s
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/predictor.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/predictor.cpp.s
.PHONY : engine/predictor.cpp.s

engine/register_model.o: engine/register_model.cpp.o

.PHONY : engine/register_model.o

# target to build an object file
engine/register_model.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/register_model.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/register_model.cpp.o
.PHONY : engine/register_model.cpp.o

engine/register_model.i: engine/register_model.cpp.i

.PHONY : engine/register_model.i

# target to preprocess a source file
engine/register_model.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/register_model.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/register_model.cpp.i
.PHONY : engine/register_model.cpp.i

engine/register_model.s: engine/register_model.cpp.s

.PHONY : engine/register_model.s

# target to generate assembly for a file
engine/register_model.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/register_model.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/register_model.cpp.s
.PHONY : engine/register_model.cpp.s

engine/reorient.o: engine/reorient.cpp.o

.PHONY : engine/reorient.o

# target to build an object file
engine/reorient.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/reorient.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/reorient.cpp.o
.PHONY : engine/reorient.cpp.o

engine/reorient.i: engine/reorient.cpp.i

.PHONY : engine/reorient.i

# target to preprocess a source file
engine/reorient.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/reorient.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/reorient.cpp.i
.PHONY : engine/reorient.cpp.i

engine/reorient.s: engine/reorient.cpp.s

.PHONY : engine/reorient.s

# target to generate assembly for a file
engine/reorient.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/reorient.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/reorient.cpp.s
.PHONY : engine/reorient.cpp.s

engine/save.o: engine/save.cpp.o

.PHONY : engine/save.o

# target to build an object file
engine/save.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/save.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/save.cpp.o
.PHONY : engine/save.cpp.o

engine/save.i: engine/save.cpp.i

.PHONY : engine/save.i

# target to preprocess a source file
engine/save.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/save.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/save.cpp.i
.PHONY : engine/save.cpp.i

engine/save.s: engine/save.cpp.s

.PHONY : engine/save.s

# target to generate assembly for a file
engine/save.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/save.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/save.cpp.s
.PHONY : engine/save.cpp.s

engine/scan.o: engine/scan.cpp.o

.PHONY : engine/scan.o

# target to build an object file
engine/scan.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/scan.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/scan.cpp.o
.PHONY : engine/scan.cpp.o

engine/scan.i: engine/scan.cpp.i

.PHONY : engine/scan.i

# target to preprocess a source file
engine/scan.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/scan.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/scan.cpp.i
.PHONY : engine/scan.cpp.i

engine/scan.s: engine/scan.cpp.s

.PHONY : engine/scan.s

# target to generate assembly for a file
engine/scan.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/scan.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/scan.cpp.s
.PHONY : engine/scan.cpp.s

engine/select.o: engine/select.cpp.o

.PHONY : engine/select.o

# target to build an object file
engine/select.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/select.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/select.cpp.o
.PHONY : engine/select.cpp.o

engine/select.i: engine/select.cpp.i

.PHONY : engine/select.i

# target to preprocess a source file
engine/select.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/select.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/select.cpp.i
.PHONY : engine/select.cpp.i

engine/select.s: engine/select.cpp.s

.PHONY : engine/select.s

# target to generate assembly for a file
engine/select.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/select.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/select.cpp.s
.PHONY : engine/select.cpp.s

engine/show.o: engine/show.cpp.o

.PHONY : engine/show.o

# target to build an object file
engine/show.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/show.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/show.cpp.o
.PHONY : engine/show.cpp.o

engine/show.i: engine/show.cpp.i

.PHONY : engine/show.i

# target to preprocess a source file
engine/show.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/show.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/show.cpp.i
.PHONY : engine/show.cpp.i

engine/show.s: engine/show.cpp.s

.PHONY : engine/show.s

# target to generate assembly for a file
engine/show.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/show.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/show.cpp.s
.PHONY : engine/show.cpp.s

engine/split.o: engine/split.cpp.o

.PHONY : engine/split.o

# target to build an object file
engine/split.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/split.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/split.cpp.o
.PHONY : engine/split.cpp.o

engine/split.i: engine/split.cpp.i

.PHONY : engine/split.i

# target to preprocess a source file
engine/split.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/split.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/split.cpp.i
.PHONY : engine/split.cpp.i

engine/split.s: engine/split.cpp.s

.PHONY : engine/split.s

# target to generate assembly for a file
engine/split.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/split.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/split.cpp.s
.PHONY : engine/split.cpp.s

engine/store.o: engine/store.cpp.o

.PHONY : engine/store.o

# target to build an object file
engine/store.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/store.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/store.cpp.o
.PHONY : engine/store.cpp.o

engine/store.i: engine/store.cpp.i

.PHONY : engine/store.i

# target to preprocess a source file
engine/store.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/store.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/store.cpp.i
.PHONY : engine/store.cpp.i

engine/store.s: engine/store.cpp.s

.PHONY : engine/store.s

# target to generate assembly for a file
engine/store.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/store.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/store.cpp.s
.PHONY : engine/store.cpp.s

engine/subset.o: engine/subset.cpp.o

.PHONY : engine/subset.o

# target to build an object file
engine/subset.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/subset.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/subset.cpp.o
.PHONY : engine/subset.cpp.o

engine/subset.i: engine/subset.cpp.i

.PHONY : engine/subset.i

# target to preprocess a source file
engine/subset.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/subset.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/subset.cpp.i
.PHONY : engine/subset.cpp.i

engine/subset.s: engine/subset.cpp.s

.PHONY : engine/subset.s

# target to generate assembly for a file
engine/subset.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/subset.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/subset.cpp.s
.PHONY : engine/subset.cpp.s

engine/user_defined.o: engine/user_defined.cpp.o

.PHONY : engine/user_defined.o

# target to build an object file
engine/user_defined.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/user_defined.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/user_defined.cpp.o
.PHONY : engine/user_defined.cpp.o

engine/user_defined.i: engine/user_defined.cpp.i

.PHONY : engine/user_defined.i

# target to preprocess a source file
engine/user_defined.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/user_defined.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/user_defined.cpp.i
.PHONY : engine/user_defined.cpp.i

engine/user_defined.s: engine/user_defined.cpp.s

.PHONY : engine/user_defined.s

# target to generate assembly for a file
engine/user_defined.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/engine/user_defined.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/engine/user_defined.cpp.s
.PHONY : engine/user_defined.cpp.s

lib/savime_lib.o: lib/savime_lib.cpp.o

.PHONY : lib/savime_lib.o

# target to build an object file
lib/savime_lib.cpp.o:
	$(MAKE) -f CMakeFiles/savime.dir/build.make CMakeFiles/savime.dir/lib/savime_lib.cpp.o
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/lib/savime_lib.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/lib/savime_lib.cpp.o
.PHONY : lib/savime_lib.cpp.o

lib/savime_lib.i: lib/savime_lib.cpp.i

.PHONY : lib/savime_lib.i

# target to preprocess a source file
lib/savime_lib.cpp.i:
	$(MAKE) -f CMakeFiles/savime.dir/build.make CMakeFiles/savime.dir/lib/savime_lib.cpp.i
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/lib/savime_lib.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/lib/savime_lib.cpp.i
.PHONY : lib/savime_lib.cpp.i

lib/savime_lib.s: lib/savime_lib.cpp.s

.PHONY : lib/savime_lib.s

# target to generate assembly for a file
lib/savime_lib.cpp.s:
	$(MAKE) -f CMakeFiles/savime.dir/build.make CMakeFiles/savime.dir/lib/savime_lib.cpp.s
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/lib/savime_lib.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/lib/savime_lib.cpp.s
.PHONY : lib/savime_lib.cpp.s

metada/default_metadata_manager.o: metada/default_metadata_manager.cpp.o

.PHONY : metada/default_metadata_manager.o

# target to build an object file
metada/default_metadata_manager.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/metada/default_metadata_manager.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/metada/default_metadata_manager.cpp.o
.PHONY : metada/default_metadata_manager.cpp.o

metada/default_metadata_manager.i: metada/default_metadata_manager.cpp.i

.PHONY : metada/default_metadata_manager.i

# target to preprocess a source file
metada/default_metadata_manager.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/metada/default_metadata_manager.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/metada/default_metadata_manager.cpp.i
.PHONY : metada/default_metadata_manager.cpp.i

metada/default_metadata_manager.s: metada/default_metadata_manager.cpp.s

.PHONY : metada/default_metadata_manager.s

# target to generate assembly for a file
metada/default_metadata_manager.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/metada/default_metadata_manager.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/metada/default_metadata_manager.cpp.s
.PHONY : metada/default_metadata_manager.cpp.s

optimizer/default_optimizer.o: optimizer/default_optimizer.cpp.o

.PHONY : optimizer/default_optimizer.o

# target to build an object file
optimizer/default_optimizer.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/optimizer/default_optimizer.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/optimizer/default_optimizer.cpp.o
.PHONY : optimizer/default_optimizer.cpp.o

optimizer/default_optimizer.i: optimizer/default_optimizer.cpp.i

.PHONY : optimizer/default_optimizer.i

# target to preprocess a source file
optimizer/default_optimizer.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/optimizer/default_optimizer.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/optimizer/default_optimizer.cpp.i
.PHONY : optimizer/default_optimizer.cpp.i

optimizer/default_optimizer.s: optimizer/default_optimizer.cpp.s

.PHONY : optimizer/default_optimizer.s

# target to generate assembly for a file
optimizer/default_optimizer.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/optimizer/default_optimizer.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/optimizer/default_optimizer.cpp.s
.PHONY : optimizer/default_optimizer.cpp.s

optimizer/dependency_checker.o: optimizer/dependency_checker.cpp.o

.PHONY : optimizer/dependency_checker.o

# target to build an object file
optimizer/dependency_checker.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/optimizer/dependency_checker.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/optimizer/dependency_checker.cpp.o
.PHONY : optimizer/dependency_checker.cpp.o

optimizer/dependency_checker.i: optimizer/dependency_checker.cpp.i

.PHONY : optimizer/dependency_checker.i

# target to preprocess a source file
optimizer/dependency_checker.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/optimizer/dependency_checker.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/optimizer/dependency_checker.cpp.i
.PHONY : optimizer/dependency_checker.cpp.i

optimizer/dependency_checker.s: optimizer/dependency_checker.cpp.s

.PHONY : optimizer/dependency_checker.s

# target to generate assembly for a file
optimizer/dependency_checker.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/optimizer/dependency_checker.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/optimizer/dependency_checker.cpp.s
.PHONY : optimizer/dependency_checker.cpp.s

optimizer/operation_splitter.o: optimizer/operation_splitter.cpp.o

.PHONY : optimizer/operation_splitter.o

# target to build an object file
optimizer/operation_splitter.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/optimizer/operation_splitter.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/optimizer/operation_splitter.cpp.o
.PHONY : optimizer/operation_splitter.cpp.o

optimizer/operation_splitter.i: optimizer/operation_splitter.cpp.i

.PHONY : optimizer/operation_splitter.i

# target to preprocess a source file
optimizer/operation_splitter.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/optimizer/operation_splitter.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/optimizer/operation_splitter.cpp.i
.PHONY : optimizer/operation_splitter.cpp.i

optimizer/operation_splitter.s: optimizer/operation_splitter.cpp.s

.PHONY : optimizer/operation_splitter.s

# target to generate assembly for a file
optimizer/operation_splitter.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/optimizer/operation_splitter.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/optimizer/operation_splitter.cpp.s
.PHONY : optimizer/operation_splitter.cpp.s

optimizer/query_cost.o: optimizer/query_cost.cpp.o

.PHONY : optimizer/query_cost.o

# target to build an object file
optimizer/query_cost.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/optimizer/query_cost.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/optimizer/query_cost.cpp.o
.PHONY : optimizer/query_cost.cpp.o

optimizer/query_cost.i: optimizer/query_cost.cpp.i

.PHONY : optimizer/query_cost.i

# target to preprocess a source file
optimizer/query_cost.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/optimizer/query_cost.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/optimizer/query_cost.cpp.i
.PHONY : optimizer/query_cost.cpp.i

optimizer/query_cost.s: optimizer/query_cost.cpp.s

.PHONY : optimizer/query_cost.s

# target to generate assembly for a file
optimizer/query_cost.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/optimizer/query_cost.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/optimizer/query_cost.cpp.s
.PHONY : optimizer/query_cost.cpp.s

optimizer/query_graph.o: optimizer/query_graph.cpp.o

.PHONY : optimizer/query_graph.o

# target to build an object file
optimizer/query_graph.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/optimizer/query_graph.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/optimizer/query_graph.cpp.o
.PHONY : optimizer/query_graph.cpp.o

optimizer/query_graph.i: optimizer/query_graph.cpp.i

.PHONY : optimizer/query_graph.i

# target to preprocess a source file
optimizer/query_graph.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/optimizer/query_graph.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/optimizer/query_graph.cpp.i
.PHONY : optimizer/query_graph.cpp.i

optimizer/query_graph.s: optimizer/query_graph.cpp.s

.PHONY : optimizer/query_graph.s

# target to generate assembly for a file
optimizer/query_graph.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/optimizer/query_graph.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/optimizer/query_graph.cpp.s
.PHONY : optimizer/query_graph.cpp.s

parser/bison.o: parser/bison.cpp.o

.PHONY : parser/bison.o

# target to build an object file
parser/bison.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/parser/bison.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/parser/bison.cpp.o
.PHONY : parser/bison.cpp.o

parser/bison.i: parser/bison.cpp.i

.PHONY : parser/bison.i

# target to preprocess a source file
parser/bison.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/parser/bison.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/parser/bison.cpp.i
.PHONY : parser/bison.cpp.i

parser/bison.s: parser/bison.cpp.s

.PHONY : parser/bison.s

# target to generate assembly for a file
parser/bison.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/parser/bison.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/parser/bison.cpp.s
.PHONY : parser/bison.cpp.s

parser/default_parser.o: parser/default_parser.cpp.o

.PHONY : parser/default_parser.o

# target to build an object file
parser/default_parser.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/parser/default_parser.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/parser/default_parser.cpp.o
.PHONY : parser/default_parser.cpp.o

parser/default_parser.i: parser/default_parser.cpp.i

.PHONY : parser/default_parser.i

# target to preprocess a source file
parser/default_parser.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/parser/default_parser.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/parser/default_parser.cpp.i
.PHONY : parser/default_parser.cpp.i

parser/default_parser.s: parser/default_parser.cpp.s

.PHONY : parser/default_parser.s

# target to generate assembly for a file
parser/default_parser.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/parser/default_parser.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/parser/default_parser.cpp.s
.PHONY : parser/default_parser.cpp.s

parser/flex.o: parser/flex.cpp.o

.PHONY : parser/flex.o

# target to build an object file
parser/flex.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/parser/flex.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/parser/flex.cpp.o
.PHONY : parser/flex.cpp.o

parser/flex.i: parser/flex.cpp.i

.PHONY : parser/flex.i

# target to preprocess a source file
parser/flex.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/parser/flex.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/parser/flex.cpp.i
.PHONY : parser/flex.cpp.i

parser/flex.s: parser/flex.cpp.s

.PHONY : parser/flex.s

# target to generate assembly for a file
parser/flex.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/parser/flex.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/parser/flex.cpp.s
.PHONY : parser/flex.cpp.s

parser/register_model_parser.o: parser/register_model_parser.cpp.o

.PHONY : parser/register_model_parser.o

# target to build an object file
parser/register_model_parser.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/parser/register_model_parser.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/parser/register_model_parser.cpp.o
.PHONY : parser/register_model_parser.cpp.o

parser/register_model_parser.i: parser/register_model_parser.cpp.i

.PHONY : parser/register_model_parser.i

# target to preprocess a source file
parser/register_model_parser.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/parser/register_model_parser.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/parser/register_model_parser.cpp.i
.PHONY : parser/register_model_parser.cpp.i

parser/register_model_parser.s: parser/register_model_parser.cpp.s

.PHONY : parser/register_model_parser.s

# target to generate assembly for a file
parser/register_model_parser.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/parser/register_model_parser.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/parser/register_model_parser.cpp.s
.PHONY : parser/register_model_parser.cpp.s

parser/schema_builder.o: parser/schema_builder.cpp.o

.PHONY : parser/schema_builder.o

# target to build an object file
parser/schema_builder.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/parser/schema_builder.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/parser/schema_builder.cpp.o
.PHONY : parser/schema_builder.cpp.o

parser/schema_builder.i: parser/schema_builder.cpp.i

.PHONY : parser/schema_builder.i

# target to preprocess a source file
parser/schema_builder.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/parser/schema_builder.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/parser/schema_builder.cpp.i
.PHONY : parser/schema_builder.cpp.i

parser/schema_builder.s: parser/schema_builder.cpp.s

.PHONY : parser/schema_builder.s

# target to generate assembly for a file
parser/schema_builder.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/parser/schema_builder.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/parser/schema_builder.cpp.s
.PHONY : parser/schema_builder.cpp.s

query/default_query_data_manager.o: query/default_query_data_manager.cpp.o

.PHONY : query/default_query_data_manager.o

# target to build an object file
query/default_query_data_manager.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/query/default_query_data_manager.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/query/default_query_data_manager.cpp.o
.PHONY : query/default_query_data_manager.cpp.o

query/default_query_data_manager.i: query/default_query_data_manager.cpp.i

.PHONY : query/default_query_data_manager.i

# target to preprocess a source file
query/default_query_data_manager.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/query/default_query_data_manager.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/query/default_query_data_manager.cpp.i
.PHONY : query/default_query_data_manager.cpp.i

query/default_query_data_manager.s: query/default_query_data_manager.cpp.s

.PHONY : query/default_query_data_manager.s

# target to generate assembly for a file
query/default_query_data_manager.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/query/default_query_data_manager.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/query/default_query_data_manager.cpp.s
.PHONY : query/default_query_data_manager.cpp.s

session/default_session.o: session/default_session.cpp.o

.PHONY : session/default_session.o

# target to build an object file
session/default_session.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/session/default_session.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/session/default_session.cpp.o
.PHONY : session/default_session.cpp.o

session/default_session.i: session/default_session.cpp.i

.PHONY : session/default_session.i

# target to preprocess a source file
session/default_session.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/session/default_session.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/session/default_session.cpp.i
.PHONY : session/default_session.cpp.i

session/default_session.s: session/default_session.cpp.s

.PHONY : session/default_session.s

# target to generate assembly for a file
session/default_session.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/session/default_session.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/session/default_session.cpp.s
.PHONY : session/default_session.cpp.s

session/default_session_manager.o: session/default_session_manager.cpp.o

.PHONY : session/default_session_manager.o

# target to build an object file
session/default_session_manager.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/session/default_session_manager.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/session/default_session_manager.cpp.o
.PHONY : session/default_session_manager.cpp.o

session/default_session_manager.i: session/default_session_manager.cpp.i

.PHONY : session/default_session_manager.i

# target to preprocess a source file
session/default_session_manager.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/session/default_session_manager.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/session/default_session_manager.cpp.i
.PHONY : session/default_session_manager.cpp.i

session/default_session_manager.s: session/default_session_manager.cpp.s

.PHONY : session/default_session_manager.s

# target to generate assembly for a file
session/default_session_manager.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/session/default_session_manager.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/session/default_session_manager.cpp.s
.PHONY : session/default_session_manager.cpp.s

spst-master/src/spst.o: spst-master/src/spst.cpp.o

.PHONY : spst-master/src/spst.o

# target to build an object file
spst-master/src/spst.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/spst-master/src/spst.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/spst-master/src/spst.cpp.o
.PHONY : spst-master/src/spst.cpp.o

spst-master/src/spst.i: spst-master/src/spst.cpp.i

.PHONY : spst-master/src/spst.i

# target to preprocess a source file
spst-master/src/spst.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/spst-master/src/spst.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/spst-master/src/spst.cpp.i
.PHONY : spst-master/src/spst.cpp.i

spst-master/src/spst.s: spst-master/src/spst.cpp.s

.PHONY : spst-master/src/spst.s

# target to generate assembly for a file
spst-master/src/spst.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/spst-master/src/spst.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/spst-master/src/spst.cpp.s
.PHONY : spst-master/src/spst.cpp.s

staging/staging_dummy.o: staging/staging_dummy.cpp.o

.PHONY : staging/staging_dummy.o

# target to build an object file
staging/staging_dummy.cpp.o:
	$(MAKE) -f CMakeFiles/savime-staging.dir/build.make CMakeFiles/savime-staging.dir/staging/staging_dummy.cpp.o
.PHONY : staging/staging_dummy.cpp.o

staging/staging_dummy.i: staging/staging_dummy.cpp.i

.PHONY : staging/staging_dummy.i

# target to preprocess a source file
staging/staging_dummy.cpp.i:
	$(MAKE) -f CMakeFiles/savime-staging.dir/build.make CMakeFiles/savime-staging.dir/staging/staging_dummy.cpp.i
.PHONY : staging/staging_dummy.cpp.i

staging/staging_dummy.s: staging/staging_dummy.cpp.s

.PHONY : staging/staging_dummy.s

# target to generate assembly for a file
staging/staging_dummy.cpp.s:
	$(MAKE) -f CMakeFiles/savime-staging.dir/build.make CMakeFiles/savime-staging.dir/staging/staging_dummy.cpp.s
.PHONY : staging/staging_dummy.cpp.s

storage/default_storage_manager.o: storage/default_storage_manager.cpp.o

.PHONY : storage/default_storage_manager.o

# target to build an object file
storage/default_storage_manager.cpp.o:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/storage/default_storage_manager.cpp.o
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/storage/default_storage_manager.cpp.o
.PHONY : storage/default_storage_manager.cpp.o

storage/default_storage_manager.i: storage/default_storage_manager.cpp.i

.PHONY : storage/default_storage_manager.i

# target to preprocess a source file
storage/default_storage_manager.cpp.i:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/storage/default_storage_manager.cpp.i
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/storage/default_storage_manager.cpp.i
.PHONY : storage/default_storage_manager.cpp.i

storage/default_storage_manager.s: storage/default_storage_manager.cpp.s

.PHONY : storage/default_storage_manager.s

# target to generate assembly for a file
storage/default_storage_manager.cpp.s:
	$(MAKE) -f CMakeFiles/savime-bin.dir/build.make CMakeFiles/savime-bin.dir/storage/default_storage_manager.cpp.s
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/storage/default_storage_manager.cpp.s
.PHONY : storage/default_storage_manager.cpp.s

test/engine/engine_test.o: test/engine/engine_test.cpp.o

.PHONY : test/engine/engine_test.o

# target to build an object file
test/engine/engine_test.cpp.o:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/engine/engine_test.cpp.o
.PHONY : test/engine/engine_test.cpp.o

test/engine/engine_test.i: test/engine/engine_test.cpp.i

.PHONY : test/engine/engine_test.i

# target to preprocess a source file
test/engine/engine_test.cpp.i:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/engine/engine_test.cpp.i
.PHONY : test/engine/engine_test.cpp.i

test/engine/engine_test.s: test/engine/engine_test.cpp.s

.PHONY : test/engine/engine_test.s

# target to generate assembly for a file
test/engine/engine_test.cpp.s:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/engine/engine_test.cpp.s
.PHONY : test/engine/engine_test.cpp.s

test/engine/mock_engine.o: test/engine/mock_engine.cpp.o

.PHONY : test/engine/mock_engine.o

# target to build an object file
test/engine/mock_engine.cpp.o:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/engine/mock_engine.cpp.o
.PHONY : test/engine/mock_engine.cpp.o

test/engine/mock_engine.i: test/engine/mock_engine.cpp.i

.PHONY : test/engine/mock_engine.i

# target to preprocess a source file
test/engine/mock_engine.cpp.i:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/engine/mock_engine.cpp.i
.PHONY : test/engine/mock_engine.cpp.i

test/engine/mock_engine.s: test/engine/mock_engine.cpp.s

.PHONY : test/engine/mock_engine.s

# target to generate assembly for a file
test/engine/mock_engine.cpp.s:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/engine/mock_engine.cpp.s
.PHONY : test/engine/mock_engine.cpp.s

test/metadata/metadata_test.o: test/metadata/metadata_test.cpp.o

.PHONY : test/metadata/metadata_test.o

# target to build an object file
test/metadata/metadata_test.cpp.o:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/metadata/metadata_test.cpp.o
.PHONY : test/metadata/metadata_test.cpp.o

test/metadata/metadata_test.i: test/metadata/metadata_test.cpp.i

.PHONY : test/metadata/metadata_test.i

# target to preprocess a source file
test/metadata/metadata_test.cpp.i:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/metadata/metadata_test.cpp.i
.PHONY : test/metadata/metadata_test.cpp.i

test/metadata/metadata_test.s: test/metadata/metadata_test.cpp.s

.PHONY : test/metadata/metadata_test.s

# target to generate assembly for a file
test/metadata/metadata_test.cpp.s:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/metadata/metadata_test.cpp.s
.PHONY : test/metadata/metadata_test.cpp.s

test/mock_builder.o: test/mock_builder.cpp.o

.PHONY : test/mock_builder.o

# target to build an object file
test/mock_builder.cpp.o:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/mock_builder.cpp.o
.PHONY : test/mock_builder.cpp.o

test/mock_builder.i: test/mock_builder.cpp.i

.PHONY : test/mock_builder.i

# target to preprocess a source file
test/mock_builder.cpp.i:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/mock_builder.cpp.i
.PHONY : test/mock_builder.cpp.i

test/mock_builder.s: test/mock_builder.cpp.s

.PHONY : test/mock_builder.s

# target to generate assembly for a file
test/mock_builder.cpp.s:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/mock_builder.cpp.s
.PHONY : test/mock_builder.cpp.s

test/optimizer/test_optimizer.o: test/optimizer/test_optimizer.cpp.o

.PHONY : test/optimizer/test_optimizer.o

# target to build an object file
test/optimizer/test_optimizer.cpp.o:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/optimizer/test_optimizer.cpp.o
.PHONY : test/optimizer/test_optimizer.cpp.o

test/optimizer/test_optimizer.i: test/optimizer/test_optimizer.cpp.i

.PHONY : test/optimizer/test_optimizer.i

# target to preprocess a source file
test/optimizer/test_optimizer.cpp.i:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/optimizer/test_optimizer.cpp.i
.PHONY : test/optimizer/test_optimizer.cpp.i

test/optimizer/test_optimizer.s: test/optimizer/test_optimizer.cpp.s

.PHONY : test/optimizer/test_optimizer.s

# target to generate assembly for a file
test/optimizer/test_optimizer.cpp.s:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/optimizer/test_optimizer.cpp.s
.PHONY : test/optimizer/test_optimizer.cpp.s

test/parser/parser_test.o: test/parser/parser_test.cpp.o

.PHONY : test/parser/parser_test.o

# target to build an object file
test/parser/parser_test.cpp.o:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/parser/parser_test.cpp.o
.PHONY : test/parser/parser_test.cpp.o

test/parser/parser_test.i: test/parser/parser_test.cpp.i

.PHONY : test/parser/parser_test.i

# target to preprocess a source file
test/parser/parser_test.cpp.i:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/parser/parser_test.cpp.i
.PHONY : test/parser/parser_test.cpp.i

test/parser/parser_test.s: test/parser/parser_test.cpp.s

.PHONY : test/parser/parser_test.s

# target to generate assembly for a file
test/parser/parser_test.cpp.s:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/parser/parser_test.cpp.s
.PHONY : test/parser/parser_test.cpp.s

test/query/teste_query_data.o: test/query/teste_query_data.cpp.o

.PHONY : test/query/teste_query_data.o

# target to build an object file
test/query/teste_query_data.cpp.o:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/query/teste_query_data.cpp.o
.PHONY : test/query/teste_query_data.cpp.o

test/query/teste_query_data.i: test/query/teste_query_data.cpp.i

.PHONY : test/query/teste_query_data.i

# target to preprocess a source file
test/query/teste_query_data.cpp.i:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/query/teste_query_data.cpp.i
.PHONY : test/query/teste_query_data.cpp.i

test/query/teste_query_data.s: test/query/teste_query_data.cpp.s

.PHONY : test/query/teste_query_data.s

# target to generate assembly for a file
test/query/teste_query_data.cpp.s:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/query/teste_query_data.cpp.s
.PHONY : test/query/teste_query_data.cpp.s

test/storage/mock_default_storage_manager.o: test/storage/mock_default_storage_manager.cpp.o

.PHONY : test/storage/mock_default_storage_manager.o

# target to build an object file
test/storage/mock_default_storage_manager.cpp.o:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/storage/mock_default_storage_manager.cpp.o
.PHONY : test/storage/mock_default_storage_manager.cpp.o

test/storage/mock_default_storage_manager.i: test/storage/mock_default_storage_manager.cpp.i

.PHONY : test/storage/mock_default_storage_manager.i

# target to preprocess a source file
test/storage/mock_default_storage_manager.cpp.i:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/storage/mock_default_storage_manager.cpp.i
.PHONY : test/storage/mock_default_storage_manager.cpp.i

test/storage/mock_default_storage_manager.s: test/storage/mock_default_storage_manager.cpp.s

.PHONY : test/storage/mock_default_storage_manager.s

# target to generate assembly for a file
test/storage/mock_default_storage_manager.cpp.s:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/storage/mock_default_storage_manager.cpp.s
.PHONY : test/storage/mock_default_storage_manager.cpp.s

test/storage/storage_test.o: test/storage/storage_test.cpp.o

.PHONY : test/storage/storage_test.o

# target to build an object file
test/storage/storage_test.cpp.o:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/storage/storage_test.cpp.o
.PHONY : test/storage/storage_test.cpp.o

test/storage/storage_test.i: test/storage/storage_test.cpp.i

.PHONY : test/storage/storage_test.i

# target to preprocess a source file
test/storage/storage_test.cpp.i:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/storage/storage_test.cpp.i
.PHONY : test/storage/storage_test.cpp.i

test/storage/storage_test.s: test/storage/storage_test.cpp.s

.PHONY : test/storage/storage_test.s

# target to generate assembly for a file
test/storage/storage_test.cpp.s:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/storage/storage_test.cpp.s
.PHONY : test/storage/storage_test.cpp.s

test/test_main.o: test/test_main.cpp.o

.PHONY : test/test_main.o

# target to build an object file
test/test_main.cpp.o:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/test_main.cpp.o
.PHONY : test/test_main.cpp.o

test/test_main.i: test/test_main.cpp.i

.PHONY : test/test_main.i

# target to preprocess a source file
test/test_main.cpp.i:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/test_main.cpp.i
.PHONY : test/test_main.cpp.i

test/test_main.s: test/test_main.cpp.s

.PHONY : test/test_main.s

# target to generate assembly for a file
test/test_main.cpp.s:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/test_main.cpp.s
.PHONY : test/test_main.cpp.s

test/test_queries_creator.o: test/test_queries_creator.cpp.o

.PHONY : test/test_queries_creator.o

# target to build an object file
test/test_queries_creator.cpp.o:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/test_queries_creator.cpp.o
.PHONY : test/test_queries_creator.cpp.o

test/test_queries_creator.i: test/test_queries_creator.cpp.i

.PHONY : test/test_queries_creator.i

# target to preprocess a source file
test/test_queries_creator.cpp.i:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/test_queries_creator.cpp.i
.PHONY : test/test_queries_creator.cpp.i

test/test_queries_creator.s: test/test_queries_creator.cpp.s

.PHONY : test/test_queries_creator.s

# target to generate assembly for a file
test/test_queries_creator.cpp.s:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/test_queries_creator.cpp.s
.PHONY : test/test_queries_creator.cpp.s

test/test_queries_results.o: test/test_queries_results.cpp.o

.PHONY : test/test_queries_results.o

# target to build an object file
test/test_queries_results.cpp.o:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/test_queries_results.cpp.o
.PHONY : test/test_queries_results.cpp.o

test/test_queries_results.i: test/test_queries_results.cpp.i

.PHONY : test/test_queries_results.i

# target to preprocess a source file
test/test_queries_results.cpp.i:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/test_queries_results.cpp.i
.PHONY : test/test_queries_results.cpp.i

test/test_queries_results.s: test/test_queries_results.cpp.s

.PHONY : test/test_queries_results.s

# target to generate assembly for a file
test/test_queries_results.cpp.s:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/test_queries_results.cpp.s
.PHONY : test/test_queries_results.cpp.s

test/test_utils.o: test/test_utils.cpp.o

.PHONY : test/test_utils.o

# target to build an object file
test/test_utils.cpp.o:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/test_utils.cpp.o
.PHONY : test/test_utils.cpp.o

test/test_utils.i: test/test_utils.cpp.i

.PHONY : test/test_utils.i

# target to preprocess a source file
test/test_utils.cpp.i:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/test_utils.cpp.i
.PHONY : test/test_utils.cpp.i

test/test_utils.s: test/test_utils.cpp.s

.PHONY : test/test_utils.s

# target to generate assembly for a file
test/test_utils.cpp.s:
	$(MAKE) -f CMakeFiles/savime-test.dir/build.make CMakeFiles/savime-test.dir/test/test_utils.cpp.s
.PHONY : test/test_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... install/strip"
	@echo "... savimec"
	@echo "... rebuild_cache"
	@echo "... savime"
	@echo "... savime-bin"
	@echo "... edit_cache"
	@echo "... savime-test"
	@echo "... savime-staging"
	@echo "... client/client.o"
	@echo "... client/client.i"
	@echo "... client/client.s"
	@echo "... configuration/default_config_manager.o"
	@echo "... configuration/default_config_manager.i"
	@echo "... configuration/default_config_manager.s"
	@echo "... configuration/model_configuration_manager.o"
	@echo "... configuration/model_configuration_manager.i"
	@echo "... configuration/model_configuration_manager.s"
	@echo "... connection/default_connection_manager.o"
	@echo "... connection/default_connection_manager.i"
	@echo "... connection/default_connection_manager.s"
	@echo "... core/builder.o"
	@echo "... core/builder.i"
	@echo "... core/builder.s"
	@echo "... core/main.o"
	@echo "... core/main.i"
	@echo "... core/main.s"
	@echo "... core/metadata.o"
	@echo "... core/metadata.i"
	@echo "... core/metadata.s"
	@echo "... core/query_data_manager.o"
	@echo "... core/query_data_manager.i"
	@echo "... core/query_data_manager.s"
	@echo "... core/system_logger.o"
	@echo "... core/system_logger.i"
	@echo "... core/system_logger.s"
	@echo "... engine/aggregate.o"
	@echo "... engine/aggregate.i"
	@echo "... engine/aggregate.s"
	@echo "... engine/arithmetic.o"
	@echo "... engine/arithmetic.i"
	@echo "... engine/arithmetic.s"
	@echo "... engine/comparison.o"
	@echo "... engine/comparison.i"
	@echo "... engine/comparison.s"
	@echo "... engine/create_dataset.o"
	@echo "... engine/create_dataset.i"
	@echo "... engine/create_dataset.s"
	@echo "... engine/create_tar.o"
	@echo "... engine/create_tar.i"
	@echo "... engine/create_tar.s"
	@echo "... engine/create_tars.o"
	@echo "... engine/create_tars.i"
	@echo "... engine/create_tars.s"
	@echo "... engine/create_type.o"
	@echo "... engine/create_type.i"
	@echo "... engine/create_type.s"
	@echo "... engine/cross_join.o"
	@echo "... engine/cross_join.i"
	@echo "... engine/cross_join.s"
	@echo "... engine/default_engine.o"
	@echo "... engine/default_engine.i"
	@echo "... engine/default_engine.s"
	@echo "... engine/dimjoin.o"
	@echo "... engine/dimjoin.i"
	@echo "... engine/dimjoin.s"
	@echo "... engine/drop_dataset.o"
	@echo "... engine/drop_dataset.i"
	@echo "... engine/drop_dataset.s"
	@echo "... engine/drop_tar.o"
	@echo "... engine/drop_tar.i"
	@echo "... engine/drop_tar.s"
	@echo "... engine/drop_tars.o"
	@echo "... engine/drop_tars.i"
	@echo "... engine/drop_tars.s"
	@echo "... engine/drop_type.o"
	@echo "... engine/drop_type.i"
	@echo "... engine/drop_type.s"
	@echo "... engine/equijoin.o"
	@echo "... engine/equijoin.i"
	@echo "... engine/equijoin.s"
	@echo "... engine/filter.o"
	@echo "... engine/filter.i"
	@echo "... engine/filter.s"
	@echo "... engine/load_subtar.o"
	@echo "... engine/load_subtar.i"
	@echo "... engine/load_subtar.s"
	@echo "... engine/logical.o"
	@echo "... engine/logical.i"
	@echo "... engine/logical.s"
	@echo "... engine/misc/curl.o"
	@echo "... engine/misc/curl.i"
	@echo "... engine/misc/curl.s"
	@echo "... engine/misc/json.o"
	@echo "... engine/misc/json.i"
	@echo "... engine/misc/json.s"
	@echo "... engine/misc/prediction_model.o"
	@echo "... engine/misc/prediction_model.i"
	@echo "... engine/misc/prediction_model.s"
	@echo "... engine/predict.o"
	@echo "... engine/predict.i"
	@echo "... engine/predict.s"
	@echo "... engine/predictor.o"
	@echo "... engine/predictor.i"
	@echo "... engine/predictor.s"
	@echo "... engine/register_model.o"
	@echo "... engine/register_model.i"
	@echo "... engine/register_model.s"
	@echo "... engine/reorient.o"
	@echo "... engine/reorient.i"
	@echo "... engine/reorient.s"
	@echo "... engine/save.o"
	@echo "... engine/save.i"
	@echo "... engine/save.s"
	@echo "... engine/scan.o"
	@echo "... engine/scan.i"
	@echo "... engine/scan.s"
	@echo "... engine/select.o"
	@echo "... engine/select.i"
	@echo "... engine/select.s"
	@echo "... engine/show.o"
	@echo "... engine/show.i"
	@echo "... engine/show.s"
	@echo "... engine/split.o"
	@echo "... engine/split.i"
	@echo "... engine/split.s"
	@echo "... engine/store.o"
	@echo "... engine/store.i"
	@echo "... engine/store.s"
	@echo "... engine/subset.o"
	@echo "... engine/subset.i"
	@echo "... engine/subset.s"
	@echo "... engine/user_defined.o"
	@echo "... engine/user_defined.i"
	@echo "... engine/user_defined.s"
	@echo "... lib/savime_lib.o"
	@echo "... lib/savime_lib.i"
	@echo "... lib/savime_lib.s"
	@echo "... metada/default_metadata_manager.o"
	@echo "... metada/default_metadata_manager.i"
	@echo "... metada/default_metadata_manager.s"
	@echo "... optimizer/default_optimizer.o"
	@echo "... optimizer/default_optimizer.i"
	@echo "... optimizer/default_optimizer.s"
	@echo "... optimizer/dependency_checker.o"
	@echo "... optimizer/dependency_checker.i"
	@echo "... optimizer/dependency_checker.s"
	@echo "... optimizer/operation_splitter.o"
	@echo "... optimizer/operation_splitter.i"
	@echo "... optimizer/operation_splitter.s"
	@echo "... optimizer/query_cost.o"
	@echo "... optimizer/query_cost.i"
	@echo "... optimizer/query_cost.s"
	@echo "... optimizer/query_graph.o"
	@echo "... optimizer/query_graph.i"
	@echo "... optimizer/query_graph.s"
	@echo "... parser/bison.o"
	@echo "... parser/bison.i"
	@echo "... parser/bison.s"
	@echo "... parser/default_parser.o"
	@echo "... parser/default_parser.i"
	@echo "... parser/default_parser.s"
	@echo "... parser/flex.o"
	@echo "... parser/flex.i"
	@echo "... parser/flex.s"
	@echo "... parser/register_model_parser.o"
	@echo "... parser/register_model_parser.i"
	@echo "... parser/register_model_parser.s"
	@echo "... parser/schema_builder.o"
	@echo "... parser/schema_builder.i"
	@echo "... parser/schema_builder.s"
	@echo "... query/default_query_data_manager.o"
	@echo "... query/default_query_data_manager.i"
	@echo "... query/default_query_data_manager.s"
	@echo "... session/default_session.o"
	@echo "... session/default_session.i"
	@echo "... session/default_session.s"
	@echo "... session/default_session_manager.o"
	@echo "... session/default_session_manager.i"
	@echo "... session/default_session_manager.s"
	@echo "... spst-master/src/spst.o"
	@echo "... spst-master/src/spst.i"
	@echo "... spst-master/src/spst.s"
	@echo "... staging/staging_dummy.o"
	@echo "... staging/staging_dummy.i"
	@echo "... staging/staging_dummy.s"
	@echo "... storage/default_storage_manager.o"
	@echo "... storage/default_storage_manager.i"
	@echo "... storage/default_storage_manager.s"
	@echo "... test/engine/engine_test.o"
	@echo "... test/engine/engine_test.i"
	@echo "... test/engine/engine_test.s"
	@echo "... test/engine/mock_engine.o"
	@echo "... test/engine/mock_engine.i"
	@echo "... test/engine/mock_engine.s"
	@echo "... test/metadata/metadata_test.o"
	@echo "... test/metadata/metadata_test.i"
	@echo "... test/metadata/metadata_test.s"
	@echo "... test/mock_builder.o"
	@echo "... test/mock_builder.i"
	@echo "... test/mock_builder.s"
	@echo "... test/optimizer/test_optimizer.o"
	@echo "... test/optimizer/test_optimizer.i"
	@echo "... test/optimizer/test_optimizer.s"
	@echo "... test/parser/parser_test.o"
	@echo "... test/parser/parser_test.i"
	@echo "... test/parser/parser_test.s"
	@echo "... test/query/teste_query_data.o"
	@echo "... test/query/teste_query_data.i"
	@echo "... test/query/teste_query_data.s"
	@echo "... test/storage/mock_default_storage_manager.o"
	@echo "... test/storage/mock_default_storage_manager.i"
	@echo "... test/storage/mock_default_storage_manager.s"
	@echo "... test/storage/storage_test.o"
	@echo "... test/storage/storage_test.i"
	@echo "... test/storage/storage_test.s"
	@echo "... test/test_main.o"
	@echo "... test/test_main.i"
	@echo "... test/test_main.s"
	@echo "... test/test_queries_creator.o"
	@echo "... test/test_queries_creator.i"
	@echo "... test/test_queries_creator.s"
	@echo "... test/test_queries_results.o"
	@echo "... test/test_queries_results.i"
	@echo "... test/test_queries_results.s"
	@echo "... test/test_utils.o"
	@echo "... test/test_utils.i"
	@echo "... test/test_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

